---
- name: Create GCP Subnet
  hosts: 192.168.20.129
  gather_facts: no

  vars:
    gcp_service_account_file: /etc/ansible/GCP_Auth/gp-lab.json
    gcp_project: gp-lab-490903
    gcp_region: asia-south1
    gcp_network: testvpc   # Make sure this exists

  tasks:
    - name: Create subnet
      google.cloud.gcp_compute_subnetwork:
        name: my-subnet
        region: "{{ gcp_region }}"
        network: "projects/{{ gcp_project }}/global/networks/{{ gcp_network }}"
        ip_cidr_range: 192.168.1.0/24
        project: "{{ gcp_project }}"
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
