- name: Create GCP Subnet
  hosts: 192.168.20.129
  gather_facts: no

  vars:
    gcp_service_account_file: /etc/ansible/GCP_Auth/gp-lab.json
  tasks:
    - name: Create subnet
      google.cloud.gcp_compute_subnetwork:
        name: my-subnet
        region: asia-south1
        network:
          name: testvpc
        ip_cidr_range: 192.168.1.0/24
        project: gp-lab-490903
        auth_kind: serviceaccount
        service_account_file: "{{ gcp_service_account_file }}"
        state: present
